# Generated by Django 5.2.4 on 2025-08-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0004_post_disliked_alter_post_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
