# Generated by Django 5.2.4 on 2025-08-18 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0005_alter_post_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewed_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
