# Generated by Django 5.2.4 on 2025-08-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_post_viewers_alter_tag_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="commented_date",
        ),
    ]
