# Generated by Django 5.2.4 on 2025-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0007_remove_comment_commented_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
