# Generated by Django 5.2.4 on 2025-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(default="me"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_images/%Y/%m/%d/"
            ),
        ),
    ]
