# Generated by Django 5.2.4 on 2025-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_about_me_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
    ]
