# Generated by Django 5.2.4 on 2025-08-02 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
